# netlify.toml (at the root of your monorepo)

[build]
  base = "weone"
  
  # 🎯 FIX: Use the install command that bypasses strict peer dependency checks.
  command = "npm install --legacy-peer-deps && npm run build" 
  
  publish = "dist/apollo-ng/browser" # This path is relative to the 'base' directory

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200